easy_admin:
  design:
    menu:
      - { label: 'School Calendar', children: [ { entity: 'Event', label: 'List View', roles: ['ROLE_TEACHER', 'ROLE_ADMIN'] }, { label: 'Calendar View', url: '/event/1', target: '_blank' } ] }
      - { label: 'Student', children: [ { entity: 'Student', label: 'Student list', roles: ['ROLE_TEACHER', 'ROLE_ADMIN'] }, { entity: 'Grades', label: 'Grades list', role: ROLE_TEACHER } ] }
#      - { entity: 'Teacher', roles: [ROLE_ADMIN, ROLE_TEACHER] }
#      - { entity: 'Advisory', role: ROLE_ADMIN }
#      - { entity: 'Grades', label: 'Grades', role: ROLE_TEACHER }
#      - { entity: 'Homework', role: ROLE_TEACHER }
      - { entity: 'Lesson', role: ROLE_TEACHER }
      - { entity: 'Attendance', role: ROLE_TEACHER }
      - { entity: 'Activity', role: ROLE_TEACHER }
      - { label: 'Settings', children: [ { label: 'Change Password', route: 'teacher_update_password', role: ROLE_TEACHER }, { label: 'Logout', route: 'logout' } ] }
  entities:
    Event:
      roles: ['ROLE_TEACHER', 'ROLE_ADMIN']
      class: App\Entity\Event
      controller: App\Controller\EasyAdmin\EventController
      list:
        fields: ['title', 'type', 'dateStart', 'dateEnd']

    Teacher:
      roles: [ROLE_ADMIN, ROLE_TEACHER]
      disabled_actions: ['show']
      class: App\Entity\User
      controller: App\Controller\EasyAdmin\TeacherController
      search:
        fields: ['uuid', 'firstName', 'lastName']
      list:
        actions: ['new', 'edit', 'search', '-delete']
        fields:
          - { property: 'uuid', label: 'ID' }
          - { property: 'firstName', label: 'First Name' }
          - { property: 'lastName', label: 'Last Name' }
          - { property: 'email', label: 'Email' }
          - { property: 'mobileNumber', label: 'Mobile' }
          - { property: 'isActive', label: 'Is Active' }
      edit:
        actions: ['-delete']
        role: ROLE_TEACHER
        fields:
          - { property: 'plainPassword', label: 'Password', type: 'text', type_options: { required: true }, help: 'Type the plain password and system will encrypt it' }

#    Advisory:
#      role: ROLE_ADMIN
#      class: App\Entity\Advisory
#      list:
#        fields: ['id', 'section', 'teacher', 'subject']
#      new:
#        fields: ['section', 'teacher', 'subject']
#      edit:
#        fields: ['section', 'teacher', 'subject']

    Grades:
      actions: ['-delete']
      class: App\Entity\Grades
      controller: App\Controller\EasyAdmin\GradesController
      list:
        fields: ['subject', 'student', 'task', 'grade']
      edit:
        role: ROLE_TEACHER
      delete:
        role: ROLE_TEACHER

    Student:
      roles: ['ROLE_TEACHER', 'ROLE_ADMIN']
      class: App\Entity\Student
      controller: App\Controller\EasyAdmin\StudentController
      search:
        fields: ['uuid', 'firstName', 'lastName']
      show:
        actions: ['-delete']
        fields:
          - { property: 'uuid', label: 'Student ID:' }
          - { property: 'fullName' }
          - { property: 'birthday' }
          - { property: 'address' }
          - { property: 'section' }
          - { property: 'grades', label: '', type: 'embedded_list' }
      list:
        actions: ['new', 'edit', 'search', 'show', '-delete']
        fields:
          - { property: 'uuid', label: 'ID' }
          - { property: 'fullName' }
          - { property: 'section' }
          - { property: 'birthday', label: 'Birthday' }
      new:
        role: ROLE_TEACHER
        fields:
          - { property: 'firstName' }
          - { property: 'middleName' }
          - { property: 'lastName' }
          - { property: 'birthday' }
          - { property: 'address' }
          - { type: 'section' }
          - { property: 'guardian' }
          - { property: 'guardianContact' }
          - { type: 'section' }
          - { property: 'section', type_options: { required: true } }
          - { property: 'teacher', type_options: { required: true } }
      edit:
        role: ROLE_TEACHER
        actions: ['-delete']
        fields:
          - { property: 'firstName' }
          - { property: 'middleName' }
          - { property: 'lastName' }
          - { property: 'birthday' }
          - { property: 'address' }
          - { type: 'section' }
          - { property: 'guardian' }
          - { property: 'guardianContact' }
          - { type: 'section' }
          - { property: 'section', type_options: { required: true } }
          - { property: 'grades', label: '', type: 'embedded_list' }

#    Homework:
#      role: ROLE_TEACHER
#      class: App\Entity\Homework
#      controller: App\Controller\EasyAdmin\HomeworkController

    Lesson:
      roles: ['ROLE_TEACHER', 'ROLE_ADMIN']
      class: App\Entity\Lesson
      controller: App\Controller\EasyAdmin\LessonController
      list:
        roles: ['ROLE_TEACHER', 'ROLE_ADMIN']
        fields:
          - id
          - { property: 'fileName', label: 'File', template: 'file/lesson.html.twig', base_path: 'http://localhost/files/lessons' }
          - subject
          - date

    Activity:
      role: ROLE_TEACHER
      class: App\Entity\Activity
      controller: App\Controller\EasyAdmin\ActivityController
      list:
        fields:
          - id
          - { property: 'fileName', label: 'Image', type: 'image', base_path: 'http://localhost/files/activities' }
          - student
          - date

    Attendance:
      role: ROLE_TEACHER
      class: App\Entity\Attendance
      controller: App\Controller\EasyAdmin\AttendanceController
