easy_admin:
    entities:
        # List the entity class name you want to manage
        Teacher:
            class: App\Entity\User
            controller: App\Controller\TeacherController
        Student:
            class: App\Entity\Student
            controller: App\Controller\StudentController
        Attendance:
            class: App\Entity\Attendance
#            controller: App\Controller\StudentController
