easy_admin:
  entities:
    # List the entity class name you want to manage
    Teacher:
      class: App\Entity\User
      controller: App\Controller\TeacherController
      search:
        fields: ['uuid', 'firstName', 'lastName']
      list:
        actions: ['new', 'edit', 'search', '-delete']
        fields:
          - { property: 'uuid', label: 'ID' }
          - { property: 'firstName', label: 'First Name' }
          - { property: 'lastName', label: 'Last Name' }
          - { property: 'email', label: 'email' }
          - { property: 'mobileNumber', label: 'Mobile' }
          - { property: 'isActive', label: 'Is Active' }
      edit:
        actions: ['-delete']
    Student:
      class: App\Entity\Student
      controller: App\Controller\StudentController
      search:
        fields: ['uuid', 'firstName', 'lastName']
      list:
        actions: ['new', 'edit', 'search', '-delete']
        fields:
          - { property: 'uuid', label: 'ID' }
          - { property: 'firstName', label: 'First Name' }
          - { property: 'lastName', label: 'Last Name' }
          - { property: 'birthday', label: 'Birthday' }
      edit:
        actions: ['-delete']
    Attendance:
      class: App\Entity\Attendance
#      controller: App\Controller\StudentController
    Advisory:
      class: App\Entity\Advisory
#      controller: App\Controller\AdvisoryController
